### ISSUE TITLE
Comparison of different networks: failed with error

### ISSUE THREAD

**Issue by alain2208** [taehoonlee/tensornets#10]
used your code as it is to compare multiple nets and get this one 
tried with the version your provided hours ago on windows

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-cec65c313e93> in <module>()
     10 
     11 with tf.Session() as sess:
---> 12     nets.pretrained(models)
     13     for (model, img) in zip(models, imgs):
     14         preds = sess.run(model, {inputs: img})

c:\anaconda3\lib\site-packages\tensornets\pretrained.py in assign(scopes)
     56         model_name = parse_scopes(scope)[0]
     57         try:
---> 58             __load_dict__[model_name](scope)
     59         except KeyError:
     60             try:

c:\anaconda3\lib\site-packages\tensornets\pretrained.py in load_mobilenet75(scopes, return_fn)
    511         cache_subdir='models',
    512         file_hash='d4557a46a44eebfeaf08c82ae33765ed')
--> 513     values = parse_weights(weights_path)
    514     return return_fn(scopes, values)
    515 

c:\anaconda3\lib\site-packages\tensornets\utils.py in parse_weights(weights_path, move_rules)
    291     if __later_tf_version__:
    292         for (i, name) in enumerate(data['names']):
--> 293             if '/beta' in data['names'][i-1] and '/gamma' in name:
    294                 values[i], values[i-1] = values[i-1], values[i]
    295 

TypeError: a bytes-like object is required, not 'str'

**Comment by taehoonlee** [comment]
The issue has been resolved by [this patch](https://github.com/taehoonlee/tensornets/commit/001357c8f58e1d62d464aeb3b1419cca17903633). If you want to use the latest version, you can try `pip install -U --no-deps git+https://github.com/taehoonlee/tensornets`. Thank you for the comments, @alain2208!
