### ISSUE TITLE
loading multiple image at the same time

### ISSUE THREAD

**Issue by alain2208** [taehoonlee/tensornets#11]
to  process multiple image in one shot i did like this 

listim=[
    'c:/graph/1.jpg','c:/graph/2.jpg','c:/graph/3.jpg'
]

img = utils.load_img(listim, target_size=256, crop_size=224)
imgs = nets.preprocess(models, img)

got TypeError: bad argument type for built-in operation on the utils.load_img(

how to proceed if multiple image to detect?
i was trying the network comparison and so i thought it could be possible to load multiple image as it is possible to load multiple networks  in the     for (model, img) in zip(models, imgs):

**Comment by taehoonlee** [comment]
@alain2208, Please see [this commit](https://github.com/taehoonlee/tensornets/commit/c69da5ec32a1af288c70af7c37e08f6a8a19fe82). Now you can input a list of paths into `load_img`.
