### ISSUE TITLE
YOLOv3: Buffer has wrong number of dimensions

### ISSUE THREAD

**Issue by abagshaw** [taehoonlee/tensornets#16]
Sorry for all the issues opened recently 😄 No worries if you don't have time to look at this one.

Running with: Ubuntu 17.10, Python 2.7, Tensorflow-GPU 1.7.0, Nvidia K80

The following code:

```
import tensorflow as tf
import tensornets as nets

inputs = tf.placeholder(tf.float32, [None, 416, 416, 3])
model = nets.YOLOv3VOC(inputs)

img = nets.utils.load_img('cat.png')

with tf.Session() as sess:
    sess.run(model.pretrained())
    preds = sess.run(model, {inputs: model.preprocess(img)})
    boxes = model.get_boxes(preds, img.shape[1:3])
```

Produces this error:

> ValueErrorTraceback (most recent call last)
> <ipython-input-6-1ba16078b043> in <module>()
>      10     sess.run(model.pretrained())
>      11     preds = sess.run(model, {inputs: model.preprocess(img)})
> ---> 12     boxes = model.get_boxes(preds, img.shape[1:3])
> 
> /usr/local/lib/python2.7/dist-packages/tensornets/references/yolos.pyc in _get_boxes(*args, **kwargs)
>     177 def yolov3voc(x, is_training=False, scope=None, reuse=None):
>     178     def _get_boxes(*args, **kwargs):
> --> 179         return get_v3_boxes(opts('yolov3voc'), *args, **kwargs)
>     180     x = yolov3(x, [1, 2, 8, 8, 4, 3], 75, is_training, scope, reuse)
>     181     x.get_boxes = _get_boxes
> 
> /usr/local/lib/python2.7/dist-packages/tensornets/references/yolo_utils.pyc in get_v3_boxes(opts, outs, source_size, threshold)
>      77         opts['anchor_idx'] = 6 - 3 * i
>      78         o = np.array(outs[i][0], dtype=np.float32)
> ---> 79         results = yolov3_box(opts, o)
>      80         for b in results:
>      81             idx, box = parse_box(b, threshold, w, h)
> 
> /usr/local/lib/python2.7/dist-packages/tensornets/references/darkflow_utils/get_boxes.pyx in tensornets.references.darkflow_utils.get_boxes.yolov3_box()
>      53 @cython.boundscheck(False) # turn off bounds-checking for entire function
>      54 @cython.wraparound(False)  # turn off negative index wrapping for entire function
> ---> 55 def yolov3_box(meta,np.ndarray[float,ndim=3] net_out_in):
>      56     cdef:
>      57         np.intp_t H, W, _, C, B, row, col, box_loop, class_loop
> 
> ValueError: Buffer has wrong number of dimensions (expected 3, got 2)

Any ideas? Same thing happens if I run with `YOLOv3COCO`

**Comment by taehoonlee** [comment]
I think you are helping me now and I really appreciate your constant supports 👏. Don't be sorry @abagshaw.

As you know, YOLOv3 predicts at three different scales. Thus, the `sess.run(model)` must be replaced by `sess.run(model.preds)`, which returns the different-scaled feature maps. I think I should write documents about this 😂.

**Comment by taehoonlee** [comment]
[README updated](https://github.com/taehoonlee/tensornets/commit/81569434850c4926f6b408000f61292aed82fbf3).
