### ISSUE TITLE
Can't install the tensornets on Mint

### ISSUE THREAD

**Issue by songzenghui** [taehoonlee/tensornets#20]
Hi, I try to install the tensornets on Mint os by `pip install tensornets`
Here is the ERROR:
`Installing collected packages: tensornets
  Running setup.py install for tensornets ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-e0ktv6qy/tensornets/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-uv6ejby6/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/zf.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/utils.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/__init__.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/layers.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/middles.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/inceptions.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/mobilenets.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/detections.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/resnets.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/darknets.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/vggs.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/capsulenets.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/nasnets.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/densenets.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/pretrained.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/squeezenets.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/preprocess.py -> build/lib.linux-x86_64-3.5/tensornets
    copying tensornets/ops.py -> build/lib.linux-x86_64-3.5/tensornets
    creating build/lib.linux-x86_64-3.5/tensornets/datasets
    copying tensornets/datasets/__init__.py -> build/lib.linux-x86_64-3.5/tensornets/datasets
    copying tensornets/datasets/imagenet.py -> build/lib.linux-x86_64-3.5/tensornets/datasets
    copying tensornets/datasets/voc.py -> build/lib.linux-x86_64-3.5/tensornets/datasets
    creating build/lib.linux-x86_64-3.5/tensornets/references
    copying tensornets/references/__init__.py -> build/lib.linux-x86_64-3.5/tensornets/references
    copying tensornets/references/rpn_utils.py -> build/lib.linux-x86_64-3.5/tensornets/references
    copying tensornets/references/yolo_utils.py -> build/lib.linux-x86_64-3.5/tensornets/references
    copying tensornets/references/rcnns.py -> build/lib.linux-x86_64-3.5/tensornets/references
    copying tensornets/references/yolos.py -> build/lib.linux-x86_64-3.5/tensornets/references
    creating build/lib.linux-x86_64-3.5/tensornets/references/darkflow_utils
    copying tensornets/references/darkflow_utils/__init__.py -> build/lib.linux-x86_64-3.5/tensornets/references/darkflow_utils
    copying tensornets/references/darkflow_utils/box.py -> build/lib.linux-x86_64-3.5/tensornets/references/darkflow_utils
    running egg_info
    writing top-level names to tensornets.egg-info/top_level.txt
    writing dependency_links to tensornets.egg-info/dependency_links.txt
    writing tensornets.egg-info/PKG-INFO
    reading manifest file 'tensornets.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'tensornets.egg-info/SOURCES.txt'
    copying tensornets/datasets/voc.names -> build/lib.linux-x86_64-3.5/tensornets/datasets
    copying tensornets/references/coco.names -> build/lib.linux-x86_64-3.5/tensornets/references
    copying tensornets/references/voc.names -> build/lib.linux-x86_64-3.5/tensornets/references
    copying tensornets/references/darkflow_utils/__init__.pyc -> build/lib.linux-x86_64-3.5/tensornets/references/darkflow_utils
    copying tensornets/references/darkflow_utils/box.pyc -> build/lib.linux-x86_64-3.5/tensornets/references/darkflow_utils
    copying tensornets/references/darkflow_utils/get_boxes.c -> build/lib.linux-x86_64-3.5/tensornets/references/darkflow_utils
    copying tensornets/references/darkflow_utils/get_boxes.pyx -> build/lib.linux-x86_64-3.5/tensornets/references/darkflow_utils
    copying tensornets/references/darkflow_utils/get_boxes.so -> build/lib.linux-x86_64-3.5/tensornets/references/darkflow_utils
    copying tensornets/references/darkflow_utils/nms.c -> build/lib.linux-x86_64-3.5/tensornets/references/darkflow_utils
    copying tensornets/references/darkflow_utils/nms.pxd -> build/lib.linux-x86_64-3.5/tensornets/references/darkflow_utils
    copying tensornets/references/darkflow_utils/nms.pyx -> build/lib.linux-x86_64-3.5/tensornets/references/darkflow_utils
    copying tensornets/references/darkflow_utils/nms.so -> build/lib.linux-x86_64-3.5/tensornets/references/darkflow_utils
    running build_ext
    building 'tensornets.references.darkflow_utils.nms' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/tensornets
    creating build/temp.linux-x86_64-3.5/tensornets/references
    creating build/temp.linux-x86_64-3.5/tensornets/references/darkflow_utils
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.5/dist-packages/numpy/core/include -I/usr/include/python3.5m -c tensornets/references/darkflow_utils/nms.c -o build/temp.linux-x86_64-3.5/tensornets/references/darkflow_utils/nms.o
    tensornets/references/darkflow_utils/nms.c:26:20: fatal error: Python.h: 没有那个文件或目录
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-e0ktv6qy/tensornets/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-uv6ejby6/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-e0ktv6qy/tensornets/
`
I have installed `tensorflow-gpu==1.8.0`

**Comment by taehoonlee** [comment]
I don't know Mint OS. Can you try `apt-get install python3-dev` or `yum install python3-devel`?

**Comment by taehoonlee** [comment]
@songzenghui, I'll close the issue for now. Please feel free to open it again at any time if you have time to check. I'm always ready :)
