### ISSUE TITLE
can't load the weights

### ISSUE THREAD

**Issue by haddis3** [taehoonlee/tensornets#21]
my code can run without any error in one device. when i copy the code to the another device, it crashed. 
here is the error:

>   File "/media/profyuan/新加卷2/JD_Fashion_AI/JD_Fashion_AI_original/train.py", line 204, in <module>
    main()
  File "/media/profyuan/新加卷2/JD_Fashion_AI/JD_Fashion_AI_original/train.py", line 200, in main
    run_training()
  File "/media/profyuan/新加卷2/JD_Fashion_AI/JD_Fashion_AI_original/train.py", line 152, in run_training
    sess.run(model.pretrained())
  File "/usr/local/lib/python2.7/dist-packages/tensornets/pretrained.py", line 94, in _direct
    return fun(scope, return_fn=pretrained_initializer)
  File "/usr/local/lib/python2.7/dist-packages/tensornets/pretrained.py", line 186, in load_resnet101
    return return_fn(scopes, values)
  File "/usr/local/lib/python2.7/dist-packages/tensornets/utils.py", line 292, in pretrained_initializer
    assert len(weights) == len(values), 'The sizes of symbolic and ' \
AssertionError: The sizes of symbolic and actual weights do not match.

here is my pip list:

> absl-py                            0.2.1      
adium-theme-ubuntu                 0.3.4      
astor                              0.6.2      
backports-abc                      0.5        
backports.shutil-get-terminal-size 1.0.0      
backports.weakref                  1.0.post1  
bleach                             1.5.0      
configparser                       3.5.0      
cycler                             0.9.0      
Cython                             0.28.2     
decorator                          4.0.6      
easydict                           1.7        
entrypoints                        0.2.3      
enum34                             1.1.6      
funcsigs                           1.0.2      
functools32                        3.2.3.post2
futures                            3.2.0      
gast                               0.2.0      
grpcio                             1.12.0     
h5py                               2.7.1      
html5lib                           0.9999999  
ipykernel                          4.8.2      
ipython                            5.7.0      
ipython-genutils                   0.2.0      
ipywidgets                         7.2.1      
Jinja2                             2.10       
jsonschema                         2.6.0      
jupyter                            1.0.0      
jupyter-client                     5.2.3      
jupyter-console                    5.2.0      
jupyter-core                       4.4.0      
Keras                              2.1.6      
Markdown                           2.6.11     
MarkupSafe                         1.0        
matplotlib                         1.5.1      
mistune                            0.8.3      
mock                               2.0.0      
nbconvert                          5.3.1      
nbformat                           4.4.0      
nose                               1.3.7      
notebook                           5.5.0      
numpy                              1.14.3     
opencv-python                      3.4.0.12   
pandocfilters                      1.4.2      
pathlib2                           2.3.2      
pbr                                4.0.2      
pexpect                            4.5.0      
pickleshare                        0.7.4      
Pillow                             5.1.0      
pip                                10.0.1     
prompt-toolkit                     1.0.15     
protobuf                           3.5.2.post1
ptyprocess                         0.5.2      
Pygments                           2.2.0      
pyparsing                          2.0.3      
Pyste                              0.9.10     
python-dateutil                    2.4.2      
pytz                               2014.10    
PyYAML                             3.12       
pyzmq                              17.0.0     
qtconsole                          4.3.1      
scandir                            1.7        
scikit-image                       0.10.1     
scikit-learn                       0.19.1     
scipy                              0.17.0     
Send2Trash                         1.5.0      
setuptools                         20.7.0     
simplegeneric                      0.8.1      
singledispatch                     3.4.0.3    
six                                1.10.0     
sklearn                            0.0        
tensorboard                        1.8.0      
tensorflow                         1.8.0      
tensorflow-gpu                     1.4.0      
tensorflow-tensorboard             0.4.0      
tensornets                         0.3.3      
termcolor                          1.1.0      
terminado                          0.8.1      
testpath                           0.3.1      
tornado                            5.0.2      
traitlets                          4.3.2      
unity-lens-photos                  1.0        
virtualenv                         15.0.1     
wcwidth                            0.1.7      
Werkzeug                           0.14.1     
wheel                              0.29.0     
widgetsnbextension                 3.2.1

**Comment by taehoonlee** [comment]
@haddis3, Can you share your snippets to reproduce the error?

**Comment by haddis3** [comment]
`def run_training():

    is_training = tf.placeholder(tf.bool)
    steps_per_epoch = 3000
    # learning_rate = tf.placeholder(dtype=tf.float32)
    train_filenames = ['./train.tfrecords']
    validation_filenames = ['./valid.tfrecords']
    train_datasets = tf.data.TFRecordDataset(filenames=train_filenames)
    validation_datasets = tf.data.TFRecordDataset(filenames=validation_filenames)
    train_datasets = train_datasets.map(_parse_function).batch(16).repeat()
    validation_datasets = validation_datasets.map(_parse_function).batch(1).repeat(1)
    iterator = tf.data.Iterator.from_structure(train_datasets.output_types,
                                               train_datasets.output_shapes)
    image, label = iterator.get_next()
    training_init_op = iterator.make_initializer(train_datasets)
    validation_init_op = iterator.make_initializer(validation_datasets)

    model = nets.ResNet101(image, stem=True, is_training=is_training, classes=13)     # 注意输入图片的预处理
    # model = nets.DenseNet121()
    res_feature = model.get_outputs()[128]
    scale_feature = tf.image.resize_bilinear(res_feature, [16, 16])
    fc7_ = subnet.Part_based_convolution(scale_feature)
    # x1 = tf.layers.conv2d(res_feature, filters=2048, kernel_size=3, strides=2)
    # x2 = tf.layers.conv2d(res_feature, filters=2048, kernel_size=3, strides=1)
    # compute the loss
    glob = tf.reduce_mean(model, axis=[1, 2])
    fc7 = tf.layers.dense(glob, units=13,
                          kernel_initializer=tf.contrib.layers.variance_scaling_initializer())
    out = fc7 + fc7_
    # recalibration the weights
    # reweight_fc7 = tf.layers.dense(fc7, units=13, activation=tf.nn.sigmoid,
    #               kernel_initializer=tf.contrib.layers.variance_scaling_initializer())
    # fc8 = tf.multiply(fc7, reweight_fc7)
    #

    cost = loss(out, label)
    # optimizer = tf.train.MomentumOptimizer(learning_rate=learning_rate, momentum=0.9)
    optimizer = tf.train.AdamOptimizer(learning_rate=0.0001)
    update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
    with tf.control_dependencies(update_ops):
        grads = optimizer.compute_gradients(cost)
        # record the grad of the variables
        for grad, var in grads:
            add_gradient_summary(grad, var)
        train_op = optimizer.apply_gradients(grads)

    summary_op = tf.summary.merge_all()
    saver = tf.train.Saver(max_to_keep=10)
    lr = 0.0001
    init = tf.group(tf.global_variables_initializer(), tf.local_variables_initializer())

    with tf.Session() as sess:

        sess.run(init)
        summary_writer = tf.summary.FileWriter(FLAGS.logs_dir, sess.graph)
        sess.run(model.pretrained())
        step = 0

        for _ in range(18):
            sess.run(training_init_op)  # must initialize the iterator to read the data flow
            for _ in range(3125):

                # if step / steps_per_epoch == 5:
                #     lr = 0.00001
                # elif step / steps_per_epoch == (FLAGS.epoch * 0.5):
                #     lr = 0.000001
                # elif step / steps_per_epoch == (FLAGS.epoch * 0.8):
                #     lr = 0.0000001

                start_time = time.time()
                _, loss_value = sess.run([train_op, cost], {is_training: True})
                duration = time.time() - start_time

                if step % 100 == 0:
                    print('step %d: loss = %.6f ( %.3f sec)' % (step, loss_value, duration))
                    # summary_str = sess.run(summary_op, {is_training: False})
                    # summary_writer.add_summary(summary_str, step)

                if step % 3125 == 0:
                    checkpoint_path = os.path.join(FLAGS.model_dir, 'model.ckpt')
                    saver.save(sess, save_path=checkpoint_path, global_step=step)

                step += 1
`

**Comment by taehoonlee** [comment]
@haddis3, Can you elaborate on your snippets to reproduce the error? The above snippet has no error points.

**Comment by taehoonlee** [comment]
@haddis3, I'll close the issue for now. Please feel free to open it again at any time if you have time to check. I'm always ready :)
