### ISSUE TITLE
The output problem of sharing weights.

### ISSUE THREAD

**Issue by LynnHo** [taehoonlee/tensornets#28]
I use the code like below,
```
...
resnet = partial(tensornets.ResNet50, reuse=tf.AUTO_REUSE)
outputs_1 = resnet(x_1).get_outputs()
outputs_2 = resnet(x_2).get_outputs() 
...
```
`outputs_2` appends the outputs of `x_2` to `outputs_1`.

**Comment by LynnHo** [comment]
@taehoonlee Do you have any idea? Is it a bug?

**Comment by taehoonlee** [comment]
@LynnHo, Sorry for the late reply. This is because the two models have the same prefix for the output tensors. Currently, the following is one of the workarounds:
```python
import tensorflow as tf
import tensornets as nets
from functools import partial

x_1 = tf.placeholder(tf.float32, [None, 224, 224, 3], name='x1')
x_2 = tf.placeholder(tf.float32, [None, 224, 224, 3], name='x2')

resnet = partial(nets.ResNet50, scope='resnet50', reuse=tf.AUTO_REUSE)
model1 = resnet(x_1)
with tf.name_scope('xx'):
    model2 = resnet(x_2)

assert len(model1.get_outputs()) == 161
assert len(model2.get_outputs()) == 161
assert len(model1.get_weights()) == 320
assert len(model2.get_weights()) == 320
```

If I find the elegant methods or make weight sharing more seamless, I'll let you know. Thank you for the reports!

**Comment by taehoonlee** [comment]
The recent updates address the issue you reported. Currently, I recommend the following pattern:
```python
with tf.name_scope('clone0'):
    model1 = nets.ResNet50(x1, reuse=tf.AUTO_REUSE)
with tf.name_scope('clone1'):
    model2 = nets.ResNet50(x2, reuse=tf.AUTO_REUSE)
```

These are the materials you might be interested in:
1. Fix: https://github.com/taehoonlee/tensornets/commit/ae8e431cbabda125adce6ec2b5aea7f0373d9369
2. Notes: #43
3. Test codes: https://github.com/taehoonlee/tensornets/commit/b1c253341573118a5b61ca0c7716257b9be248f0

If you want to use the latest version, you can try `pip install -U tensornets`. Please feel free to open it again at any time if you have additional comments :)

**Comment by LynnHo** [comment]
@taehoonlee Thanks for your effort！ Tensornets really helps in my works！
