### ISSUE TITLE
about some doubt

### ISSUE THREAD

**Issue by wingerliu** [taehoonlee/tensornets#29]
First thanks your repo. but i want to ask you some doubt of mine.
1. In follow image, we can see 'scope' in function __stack unuse;
![default](https://user-images.githubusercontent.com/26087367/46956275-7a13fe00-d0c7-11e8-9cb4-a4cf6844d6f9.png)
2. What is this circled in follow image.
![default](https://user-images.githubusercontent.com/26087367/46956558-3077e300-d0c8-11e8-878f-72e330ada125.png)

**Comment by taehoonlee** [comment]
Thank you for trying TensorNets, @wingerliu.

1. The `scope` is reassigned based on the default variable scope (e.g., `darknet19`, `genYOLOv2`) in [the decorator `var_scope`](https://github.com/taehoonlee/tensornets/blob/master/tensornets/utils.py#L231-L264).

2. The `x.p` is also assigned in the `var_scope`. It means the bottleneck layer.

**Comment by taehoonlee** [comment]
I'll close the issue for now. Please feel free to open it again at any time if you have additional comments, @wingerliu.
