### ISSUE TITLE
Unable to do evaluation with multi GPU.

### ISSUE THREAD

**Issue by nidhidamodaran** [taehoonlee/tensornets#30]
Though training is successful in multi-gpu cases, eval step fails with the following error:

InvalidArgumentError (see above for traceback): Number of ways to split should evenly divide the split dimension, but got split_dim 0 (size = 1) and num_split 2
	 [[Node: split_inputs/split = Split[T=DT_FLOAT, num_split=2, _device="/job:localhost/replica:0/task:0/device:CPU:0"](split_inputs/split/split_dim, IteratorGetNext)]]

My program is estimator based, training using train_and_evaluate method. Also using replicate_model_fn to run across multi GPUs

**Comment by taehoonlee** [comment]
@nidhidamodaran, Can you share your code snippet? It is not easy for me to reproduce your error without the codes.

**Comment by nidhidamodaran** [comment]
@taehoonlee , please use the attached code.
[sample_cat_dog.txt](https://github.com/taehoonlee/tensornets/files/2481277/sample_cat_dog.txt)


Dataset is from here( files.fast.ai/data/dogscats.zip )

**Comment by nidhidamodaran** [comment]
@taehoonlee , looks like bug is in tensorflow.
Code works with tf.contrib.distribute.MirroredStrategy.

Closing the issue.
