### ISSUE TITLE
Error When pip

### ISSUE THREAD

**Issue by ScroogeMucDuck** [taehoonlee/tensornets#33]
When I installed TensorNets from PyPI (pip install tensornets) , what happened as:
Building wheels for collected packages: tensornets
  Running setup.py bdist_wheel for tensornets ... error
  Complete output from command e:\python\anaconda_setup\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\hp\\AppData\\Local\\Temp\\pip-install-u8ygwt_s\\tensornets\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\hp\AppData\Local\Temp\pip-wheel-9cd_yi__ --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\tensornets
  copying tensornets\capsulenets.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\darknets.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\densenets.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\detections.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\inceptions.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\layers.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\middles.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\mobilenets.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\nasnets.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\ops.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\preprocess.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\pretrained.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\resnets.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\squeezenets.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\unet.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\utils.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\vggs.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\wavenets.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\zf.py -> build\lib.win-amd64-3.6\tensornets
  copying tensornets\__init__.py -> build\lib.win-amd64-3.6\tensornets
  creating build\lib.win-amd64-3.6\tensornets\datasets
  copying tensornets\datasets\coco.py -> build\lib.win-amd64-3.6\tensornets\datasets
  copying tensornets\datasets\imagenet.py -> build\lib.win-amd64-3.6\tensornets\datasets
  copying tensornets\datasets\voc.py -> build\lib.win-amd64-3.6\tensornets\datasets
  copying tensornets\datasets\__init__.py -> build\lib.win-amd64-3.6\tensornets\datasets
  creating build\lib.win-amd64-3.6\tensornets\references
  copying tensornets\references\rcnns.py -> build\lib.win-amd64-3.6\tensornets\references
  copying tensornets\references\rpn_utils.py -> build\lib.win-amd64-3.6\tensornets\references
  copying tensornets\references\yolos.py -> build\lib.win-amd64-3.6\tensornets\references
  copying tensornets\references\yolo_utils.py -> build\lib.win-amd64-3.6\tensornets\references
  copying tensornets\references\__init__.py -> build\lib.win-amd64-3.6\tensornets\references
  creating build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\box.py -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\__init__.py -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
  running egg_info
  writing tensornets.egg-info\PKG-INFO
  writing dependency_links to tensornets.egg-info\dependency_links.txt
  writing top-level names to tensornets.egg-info\top_level.txt
  reading manifest file 'tensornets.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'tensornets.egg-info\SOURCES.txt'
  copying tensornets\references\darkflow_utils\get_boxes.c -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\nms.c -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
  copying tensornets\datasets\coco.names -> build\lib.win-amd64-3.6\tensornets\datasets
  copying tensornets\datasets\voc.names -> build\lib.win-amd64-3.6\tensornets\datasets
  copying tensornets\references\coco.names -> build\lib.win-amd64-3.6\tensornets\references
  copying tensornets\references\voc.names -> build\lib.win-amd64-3.6\tensornets\references
  copying tensornets\references\darkflow_utils\__init__.pyc -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\box.pyc -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\get_boxes.pyx -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\get_boxes.so -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\nms.pxd -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\nms.pyx -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\nms.so -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
  running build_ext
  building 'tensornets.references.darkflow_utils.nms' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\tensornets
  creating build\temp.win-amd64-3.6\Release\tensornets\references
  creating build\temp.win-amd64-3.6\Release\tensornets\references\darkflow_utils
  D:\MSVSC\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ie:\python\anaconda_setup\lib\site-packages\numpy\core\include -Ie:\python\anaconda_setup\include -Ie:\python\anaconda_setup\include -ID:\MSVSC\VC\Tools\MSVC\14.15.26726\ATLMFC\include -ID:\MSVSC\VC\Tools\MSVC\14.15.26726\include "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tctensornets/references/darkflow_utils/nms.c /Fobuild\temp.win-amd64-3.6\Release\tensornets/references/darkflow_utils/nms.obj
  nms.c
  e:\python\anaconda_setup\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
  tensornets/references/darkflow_utils/nms.c(2437): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
  tensornets/references/darkflow_utils/nms.c(2446): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
  tensornets/references/darkflow_utils/nms.c(2496): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
  tensornets/references/darkflow_utils/nms.c(22776): warning C4244: “初始化”: 从“double”转换到“float”，可能丢失数据
  tensornets/references/darkflow_utils/nms.c(22782): warning C4244: “初始化”: 从“double”转换到“float”，可能丢失数据
  D:\MSVSC\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:e:\python\anaconda_setup\libs /LIBPATH:e:\python\anaconda_setup\PCbuild\amd64 /LIBPATH:D:\MSVSC\VC\Tools\MSVC\14.15.26726\ATLMFC\lib\x64 /LIBPATH:D:\MSVSC\VC\Tools\MSVC\14.15.26726\lib\x64 "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x64" m.lib /EXPORT:PyInit_nms build\temp.win-amd64-3.6\Release\tensornets/references/darkflow_utils/nms.obj /OUT:build\lib.win-amd64-3.6\tensornets\references\darkflow_utils\nms.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\tensornets/references/darkflow_utils\nms.cp36-win_amd64.lib
  LINK : fatal error LNK1181: 无法打开输入文件“m.lib”
  error: command 'D:\\MSVSC\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

  ----------------------------------------
  Failed building wheel for tensornets
  Running setup.py clean for tensornets
Failed to build tensornets
Installing collected packages: tensornets
  Running setup.py install for tensornets ... error
    Complete output from command e:\python\anaconda_setup\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\hp\\AppData\\Local\\Temp\\pip-install-u8ygwt_s\\tensornets\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\hp\AppData\Local\Temp\pip-record-al4vrtuo\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\tensornets
    copying tensornets\capsulenets.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\darknets.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\densenets.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\detections.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\inceptions.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\layers.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\middles.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\mobilenets.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\nasnets.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\ops.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\preprocess.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\pretrained.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\resnets.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\squeezenets.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\unet.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\utils.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\vggs.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\wavenets.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\zf.py -> build\lib.win-amd64-3.6\tensornets
    copying tensornets\__init__.py -> build\lib.win-amd64-3.6\tensornets
    creating build\lib.win-amd64-3.6\tensornets\datasets
    copying tensornets\datasets\coco.py -> build\lib.win-amd64-3.6\tensornets\datasets
    copying tensornets\datasets\imagenet.py -> build\lib.win-amd64-3.6\tensornets\datasets
    copying tensornets\datasets\voc.py -> build\lib.win-amd64-3.6\tensornets\datasets
    copying tensornets\datasets\__init__.py -> build\lib.win-amd64-3.6\tensornets\datasets
    creating build\lib.win-amd64-3.6\tensornets\references
    copying tensornets\references\rcnns.py -> build\lib.win-amd64-3.6\tensornets\references
    copying tensornets\references\rpn_utils.py -> build\lib.win-amd64-3.6\tensornets\references
    copying tensornets\references\yolos.py -> build\lib.win-amd64-3.6\tensornets\references
    copying tensornets\references\yolo_utils.py -> build\lib.win-amd64-3.6\tensornets\references
    copying tensornets\references\__init__.py -> build\lib.win-amd64-3.6\tensornets\references
    creating build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\box.py -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\__init__.py -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
    running egg_info
    writing tensornets.egg-info\PKG-INFO
    writing dependency_links to tensornets.egg-info\dependency_links.txt
    writing top-level names to tensornets.egg-info\top_level.txt
    reading manifest file 'tensornets.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'tensornets.egg-info\SOURCES.txt'
    copying tensornets\references\darkflow_utils\get_boxes.c -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\nms.c -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
    copying tensornets\datasets\coco.names -> build\lib.win-amd64-3.6\tensornets\datasets
    copying tensornets\datasets\voc.names -> build\lib.win-amd64-3.6\tensornets\datasets
    copying tensornets\references\coco.names -> build\lib.win-amd64-3.6\tensornets\references
    copying tensornets\references\voc.names -> build\lib.win-amd64-3.6\tensornets\references
    copying tensornets\references\darkflow_utils\__init__.pyc -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\box.pyc -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\get_boxes.pyx -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\get_boxes.so -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\nms.pxd -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\nms.pyx -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\nms.so -> build\lib.win-amd64-3.6\tensornets\references\darkflow_utils
    running build_ext
    building 'tensornets.references.darkflow_utils.nms' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\tensornets
    creating build\temp.win-amd64-3.6\Release\tensornets\references
    creating build\temp.win-amd64-3.6\Release\tensornets\references\darkflow_utils
    D:\MSVSC\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ie:\python\anaconda_setup\lib\site-packages\numpy\core\include -Ie:\python\anaconda_setup\include -Ie:\python\anaconda_setup\include -ID:\MSVSC\VC\Tools\MSVC\14.15.26726\ATLMFC\include -ID:\MSVSC\VC\Tools\MSVC\14.15.26726\include "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tctensornets/references/darkflow_utils/nms.c /Fobuild\temp.win-amd64-3.6\Release\tensornets/references/darkflow_utils/nms.obj
    nms.c
    e:\python\anaconda_setup\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    tensornets/references/darkflow_utils/nms.c(2437): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
    tensornets/references/darkflow_utils/nms.c(2446): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
    tensornets/references/darkflow_utils/nms.c(2496): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
    tensornets/references/darkflow_utils/nms.c(22776): warning C4244: “初始化”: 从“double”转换到“float”，可能丢失数据
    tensornets/references/darkflow_utils/nms.c(22782): warning C4244: “初始化”: 从“double”转换到“float”，可能丢失数据
    D:\MSVSC\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:e:\python\anaconda_setup\libs /LIBPATH:e:\python\anaconda_setup\PCbuild\amd64 /LIBPATH:D:\MSVSC\VC\Tools\MSVC\14.15.26726\ATLMFC\lib\x64 /LIBPATH:D:\MSVSC\VC\Tools\MSVC\14.15.26726\lib\x64 "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x64" m.lib /EXPORT:PyInit_nms build\temp.win-amd64-3.6\Release\tensornets/references/darkflow_utils/nms.obj /OUT:build\lib.win-amd64-3.6\tensornets\references\darkflow_utils\nms.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\tensornets/references/darkflow_utils\nms.cp36-win_amd64.lib
    LINK : fatal error LNK1181: 无法打开输入文件“m.lib”
    error: command 'D:\\MSVSC\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

    ----------------------------------------
Command "e:\python\anaconda_setup\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\hp\\AppData\\Local\\Temp\\pip-install-u8ygwt_s\\tensornets\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\hp\AppData\Local\Temp\pip-record-al4vrtuo\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\hp\AppData\Local\Temp\pip-install-u8ygwt_s\tensornets\

My system is windows10 and my python is 3.6, tensorflow is 1.12.0 which is based on cpu.
Can anyone help me? Please!

**Comment by ScroogeMucDuck** [comment]
Well, you are right @minooisbusy, it does work, thanks very much.

**Comment by taehoonlee** [comment]
@minooisbusy @ScroogeMucDuck Now you can install via `pip install tensornets`. Thank you for reporting the issue :)
