### ISSUE TITLE
Using YOLOv2 get_boxes for optimization

### ISSUE THREAD

**Issue by Irfanwustl** [taehoonlee/tensornets#35]

**Comment by Irfanwustl** [comment]
Hi,
I am trying to generate adversarial example for YOLOv2. I want to minimize the score of a target object until it falls below the detection threshold. But the output layer does not provide the score directly. Rather, it is calculated by the get_boxes function. Is there any way to add this function to the final layer? Any ideas how can I minimize the score?
Thanks.

**Comment by taehoonlee** [comment]
Sorry for the late reply, @Irfanwustl. The loss already includes the score you mentioned. Thus, you can modify the function `v2_loss` in `tensornets/references/yolo_utils.py` in order to minimize the score.
