### ISSUE TITLE
Anaconda python 2.7 

### ISSUE THREAD

**Issue by luitcifer** [taehoonlee/tensornets#37]
Command "C:\Users\User\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\user\\appdata\\local\\temp\\pip-install-jarbs8\\pybluez\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\user\appdata\local\temp\pip-record-rosdw0\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\user\appdata\local\temp\pip-install-jarbs8\pybluez\

**Comment by luitcifer** [comment]
(base) C:\Users\User>pip install pybluez
Collecting pybluez
  Downloading https://files.pythonhosted.org/packages/c1/98/3149481d508bee174335be6725880f00d297afebe75c15e917af8f6fe169/PyBluez-0.22.zip (109kB)
    100% |################################| 112kB 23kB/s
Building wheels for collected packages: pybluez
  Running setup.py bdist_wheel for pybluez ... error
  Complete output from command C:\Users\User\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\user\\appdata\\local\\temp\\pip-install-jarbs8\\pybluez\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\user\appdata\local\temp\pip-wheel-stslki --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\bluetooth
  copying bluetooth\ble.py -> build\lib.win-amd64-2.7\bluetooth
  copying bluetooth\bluez.py -> build\lib.win-amd64-2.7\bluetooth
  copying bluetooth\btcommon.py -> build\lib.win-amd64-2.7\bluetooth
  copying bluetooth\msbt.py -> build\lib.win-amd64-2.7\bluetooth
  copying bluetooth\osx.py -> build\lib.win-amd64-2.7\bluetooth
  copying bluetooth\widcomm.py -> build\lib.win-amd64-2.7\bluetooth
  copying bluetooth\__init__.py -> build\lib.win-amd64-2.7\bluetooth
  running build_ext
  building 'bluetooth._msbt' extension
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\msbt
  C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-IC:\Program Files\Microsoft SDKs\Windows\v6.0A\Include" -I.\port3 -IC:\Users\User\Anaconda2\include -IC:\Users\User\Anaconda2\PC /Tcmsbt\_msbt.c /Fobuild\temp.win-amd64-2.7\Release\msbt\_msbt.obj
  _msbt.c
  C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:C:\Program Files\Microsoft SDKs\Windows\v6.0A\Lib\x64" /LIBPATH:C:\Users\User\Anaconda2\libs /LIBPATH:C:\Users\User\Anaconda2\PCbuild\amd64 /LIBPATH:C:\Users\User\Anaconda2\PC\VS9.0\amd64 WS2_32.lib Irprops.lib /EXPORT:init_msbt build\temp.win-amd64-2.7\Release\msbt\_msbt.obj /OUT:build\lib.win-amd64-2.7\bluetooth\_msbt.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\msbt\_msbt.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\msbt\_msbt.pyd.manifest
  LINK : fatal error LNK1104: cannot open file 'MSVCRT.lib'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\Bin\\link.exe' failed with exit status 1104

  ----------------------------------------
  Failed building wheel for pybluez
  Running setup.py clean for pybluez
Failed to build pybluez
Installing collected packages: pybluez
  Running setup.py install for pybluez ... error
    Complete output from command C:\Users\User\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\user\\appdata\\local\\temp\\pip-install-jarbs8\\pybluez\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\user\appdata\local\temp\pip-record-rosdw0\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\bluetooth
    copying bluetooth\ble.py -> build\lib.win-amd64-2.7\bluetooth
    copying bluetooth\bluez.py -> build\lib.win-amd64-2.7\bluetooth
    copying bluetooth\btcommon.py -> build\lib.win-amd64-2.7\bluetooth
    copying bluetooth\msbt.py -> build\lib.win-amd64-2.7\bluetooth
    copying bluetooth\osx.py -> build\lib.win-amd64-2.7\bluetooth
    copying bluetooth\widcomm.py -> build\lib.win-amd64-2.7\bluetooth
    copying bluetooth\__init__.py -> build\lib.win-amd64-2.7\bluetooth
    running build_ext
    building 'bluetooth._msbt' extension
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\msbt
    C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-IC:\Program Files\Microsoft SDKs\Windows\v6.0A\Include" -I.\port3 -IC:\Users\User\Anaconda2\include -IC:\Users\User\Anaconda2\PC /Tcmsbt\_msbt.c /Fobuild\temp.win-amd64-2.7\Release\msbt\_msbt.obj
    _msbt.c
    C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:C:\Program Files\Microsoft SDKs\Windows\v6.0A\Lib\x64" /LIBPATH:C:\Users\User\Anaconda2\libs /LIBPATH:C:\Users\User\Anaconda2\PCbuild\amd64 /LIBPATH:C:\Users\User\Anaconda2\PC\VS9.0\amd64 WS2_32.lib Irprops.lib /EXPORT:init_msbt build\temp.win-amd64-2.7\Release\msbt\_msbt.obj /OUT:build\lib.win-amd64-2.7\bluetooth\_msbt.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\msbt\_msbt.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\msbt\_msbt.pyd.manifest
    LINK : fatal error LNK1104: cannot open file 'MSVCRT.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\Bin\\link.exe' failed with exit status 1104

    ----------------------------------------
Command "C:\Users\User\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\user\\appdata\\local\\temp\\pip-install-jarbs8\\pybluez\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\user\appdata\local\temp\pip-record-rosdw0\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\user\appdata\local\temp\pip-install-jarbs8\pybluez\

**Comment by luitcifer** [comment]
> (base) C:\Users\User>pip install pybluez
> Collecting pybluez
> Downloading https://files.pythonhosted.org/packages/c1/98/3149481d508bee174335be6725880f00d297afebe75c15e917af8f6fe169/PyBluez-0.22.zip (109kB)
> 100% |################################| 112kB 23kB/s
> Building wheels for collected packages: pybluez
> Running setup.py bdist_wheel for pybluez ... error
> Complete output from command C:\Users\User\Anaconda2\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\user\appdata\local\temp\pip-install-jarbs8\pybluez\setup.py';f=getattr(tokenize, 'open', open)(**file**);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, **file**, 'exec'))" bdist_wheel -d c:\users\user\appdata\local\temp\pip-wheel-stslki --python-tag cp27:
> running bdist_wheel
> running build
> running build_py
> creating build
> creating build\lib.win-amd64-2.7
> creating build\lib.win-amd64-2.7\bluetooth
> copying bluetooth\ble.py -> build\lib.win-amd64-2.7\bluetooth
> copying bluetooth\bluez.py -> build\lib.win-amd64-2.7\bluetooth
> copying bluetooth\btcommon.py -> build\lib.win-amd64-2.7\bluetooth
> copying bluetooth\msbt.py -> build\lib.win-amd64-2.7\bluetooth
> copying bluetooth\osx.py -> build\lib.win-amd64-2.7\bluetooth
> copying bluetooth\widcomm.py -> build\lib.win-amd64-2.7\bluetooth
> copying bluetooth__init__.py -> build\lib.win-amd64-2.7\bluetooth
> running build_ext
> building 'bluetooth._msbt' extension
> creating build\temp.win-amd64-2.7
> creating build\temp.win-amd64-2.7\Release
> creating build\temp.win-amd64-2.7\Release\msbt
> C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-IC:\Program Files\Microsoft SDKs\Windows\v6.0A\Include" -I.\port3 -IC:\Users\User\Anaconda2\include -IC:\Users\User\Anaconda2\PC /Tcmsbt_msbt.c /Fobuild\temp.win-amd64-2.7\Release\msbt_msbt.obj
> _msbt.c
> C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:C:\Program Files\Microsoft SDKs\Windows\v6.0A\Lib\x64" /LIBPATH:C:\Users\User\Anaconda2\libs /LIBPATH:C:\Users\User\Anaconda2\PCbuild\amd64 /LIBPATH:C:\Users\User\Anaconda2\PC\VS9.0\amd64 WS2_32.lib Irprops.lib /EXPORT:init_msbt build\temp.win-amd64-2.7\Release\msbt_msbt.obj /OUT:build\lib.win-amd64-2.7\bluetooth_msbt.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\msbt_msbt.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\msbt_msbt.pyd.manifest
> LINK : fatal error LNK1104: cannot open file 'MSVCRT.lib'
> error: command 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin\link.exe' failed with exit status 1104
> 
> Failed building wheel for pybluez
> Running setup.py clean for pybluez
> Failed to build pybluez
> Installing collected packages: pybluez
> Running setup.py install for pybluez ... error
> Complete output from command C:\Users\User\Anaconda2\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\user\appdata\local\temp\pip-install-jarbs8\pybluez\setup.py';f=getattr(tokenize, 'open', open)(**file**);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, **file**, 'exec'))" install --record c:\users\user\appdata\local\temp\pip-record-rosdw0\install-record.txt --single-version-externally-managed --compile:
> running install
> running build
> running build_py
> creating build
> creating build\lib.win-amd64-2.7
> creating build\lib.win-amd64-2.7\bluetooth
> copying bluetooth\ble.py -> build\lib.win-amd64-2.7\bluetooth
> copying bluetooth\bluez.py -> build\lib.win-amd64-2.7\bluetooth
> copying bluetooth\btcommon.py -> build\lib.win-amd64-2.7\bluetooth
> copying bluetooth\msbt.py -> build\lib.win-amd64-2.7\bluetooth
> copying bluetooth\osx.py -> build\lib.win-amd64-2.7\bluetooth
> copying bluetooth\widcomm.py -> build\lib.win-amd64-2.7\bluetooth
> copying bluetooth__init__.py -> build\lib.win-amd64-2.7\bluetooth
> running build_ext
> building 'bluetooth._msbt' extension
> creating build\temp.win-amd64-2.7
> creating build\temp.win-amd64-2.7\Release
> creating build\temp.win-amd64-2.7\Release\msbt
> C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-IC:\Program Files\Microsoft SDKs\Windows\v6.0A\Include" -I.\port3 -IC:\Users\User\Anaconda2\include -IC:\Users\User\Anaconda2\PC /Tcmsbt_msbt.c /Fobuild\temp.win-amd64-2.7\Release\msbt_msbt.obj
> _msbt.c
> C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:C:\Program Files\Microsoft SDKs\Windows\v6.0A\Lib\x64" /LIBPATH:C:\Users\User\Anaconda2\libs /LIBPATH:C:\Users\User\Anaconda2\PCbuild\amd64 /LIBPATH:C:\Users\User\Anaconda2\PC\VS9.0\amd64 WS2_32.lib Irprops.lib /EXPORT:init_msbt build\temp.win-amd64-2.7\Release\msbt_msbt.obj /OUT:build\lib.win-amd64-2.7\bluetooth_msbt.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\msbt_msbt.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\msbt_msbt.pyd.manifest
> LINK : fatal error LNK1104: cannot open file 'MSVCRT.lib'
> error: command 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Bin\link.exe' failed with exit status 1104
> 
> ```
> ----------------------------------------
> ```
> Command "C:\Users\User\Anaconda2\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\user\appdata\local\temp\pip-install-jarbs8\pybluez\setup.py';f=getattr(tokenize, 'open', open)(**file**);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, **file**, 'exec'))" install --record c:\users\user\appdata\local\temp\pip-record-rosdw0\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\user\appdata\local\temp\pip-install-jarbs8\pybluez\

how to solve this issue?

**Comment by taehoonlee** [comment]
@luitcifer, is your problem related to TensorNets?

**Comment by luitcifer** [comment]
I installed Anaconda2. But pybluez library didn't install
