### ISSUE TITLE
Why don't install "pybluez" in anaconda3 in windows10 system

### ISSUE THREAD

**Issue by luitcifer** [taehoonlee/tensornets#38]
pip install pybluez
Collecting pybluez
  Using cached https://files.pythonhosted.org/packages/c1/98/3149481d508bee174335be6725880f00d297afebe75c15e917af8f6fe169/PyBluez-0.22.zip
    Complete output from command python setup.py egg_info:
    Could not find the Windows Platform SDK

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\User\AppData\Local\Temp\pip-install-yb8lba9t\pybluez\

ho to solve this question ?
please help me!!!

**Comment by taehoonlee** [comment]
@luitcifer, Maybe you'd better ask to `https://github.com/pybluez/pybluez`.
