### ISSUE TITLE
Minor issue with name scopes

### ISSUE THREAD

**Issue by ameroyer** [taehoonlee/tensornets#40]
Hello,
I've noticed a minor issue when using name scopes (mostly for Tensorboard visualization). For instance the following code raises an error in the `utils.var_scope` wrapper:

```
with tf.name_scope('A'):
        with tf.variable_scope('B'):
            x = tf.placeholder(shape=(None, 1024, 1024, 3), dtype=tf.float32)
            y = tensornets.MobileNet100(x, stem=True)
```

It seems the problem comes from line 243 where `_scope = tf.get_variable_scope().name` only looks at variable scope while the `tf.get_collection(..., scope=_scope)` at line 124 look through variable names. 
It can be solved by replacing line 243 with `_scope = tf.contrib.framework.get_name_scope()`, but I'm not sure if it's the best workaround.

**Comment by taehoonlee** [comment]
Thank you for the report, @ameroyer.
1. Fix: https://github.com/taehoonlee/tensornets/commit/ae8e431cbabda125adce6ec2b5aea7f0373d9369
2. Notes: #43
3. Test codes: https://github.com/taehoonlee/tensornets/commit/b1c253341573118a5b61ca0c7716257b9be248f0

If you want to use the latest version, you can try `pip install -U tensornets`. Please feel free to open it again at any time if you have additional comments :)
