### ISSUE TITLE
tensornets on windows 10

### ISSUE THREAD

**Issue by rohtash0211** [taehoonlee/tensornets#44]
Hello, facing difficulties to install tensornets.

my environment is explained bellow.

OS: windows 10, windows 7
anaconda
Python version: 3.5, 3.6
tensorflow version: 1.9, 1.10
PIP version: 18.1, 10.0.1, 19.x

pip install tensornets and pip install git+https://github.com/taehoonlee/tensornets.git

Collecting git+https://github.com/taehoonlee/tensornets.git
  Cloning https://github.com/taehoonlee/tensornets.git to c:\users\admin\appdata\local\temp\pip-req-build-pslh3n1z
Building wheels for collected packages: tensornets
  Building wheel for tensornets (setup.py) ... error
  Complete output from command c:\programdata\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\admin\\AppData\\Local\\Temp\\pip-req-build-pslh3n1z\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\admin\AppData\Local\Temp\pip-wheel-kz3ibhta --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\tensornets
  copying tensornets\capsulenets.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\darknets.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\densenets.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\detections.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\inceptions.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\layers.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\middles.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\mobilenets.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\nasnets.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\ops.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\preprocess.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\pretrained.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\resnets.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\squeezenets.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\utils.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\vggs.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\wavenets.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\zf.py -> build\lib.win-amd64-3.5\tensornets
  copying tensornets\__init__.py -> build\lib.win-amd64-3.5\tensornets
  creating build\lib.win-amd64-3.5\tensornets\datasets
  copying tensornets\datasets\coco.py -> build\lib.win-amd64-3.5\tensornets\datasets
  copying tensornets\datasets\imagenet.py -> build\lib.win-amd64-3.5\tensornets\datasets
  copying tensornets\datasets\voc.py -> build\lib.win-amd64-3.5\tensornets\datasets
  copying tensornets\datasets\__init__.py -> build\lib.win-amd64-3.5\tensornets\datasets
  creating build\lib.win-amd64-3.5\tensornets\references
  copying tensornets\references\rcnns.py -> build\lib.win-amd64-3.5\tensornets\references
  copying tensornets\references\rpn_utils.py -> build\lib.win-amd64-3.5\tensornets\references
  copying tensornets\references\yolos.py -> build\lib.win-amd64-3.5\tensornets\references
  copying tensornets\references\yolo_utils.py -> build\lib.win-amd64-3.5\tensornets\references
  copying tensornets\references\__init__.py -> build\lib.win-amd64-3.5\tensornets\references
  creating build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\box.py -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\__init__.py -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  running egg_info
  creating tensornets.egg-info
  writing top-level names to tensornets.egg-info\top_level.txt
  writing tensornets.egg-info\PKG-INFO
  writing dependency_links to tensornets.egg-info\dependency_links.txt
  writing manifest file 'tensornets.egg-info\SOURCES.txt'
  reading manifest file 'tensornets.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'tensornets.egg-info\SOURCES.txt'
  copying tensornets\references\darkflow_utils\get_boxes.c -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\nms.c -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  copying tensornets\datasets\coco.names -> build\lib.win-amd64-3.5\tensornets\datasets
  copying tensornets\datasets\voc.names -> build\lib.win-amd64-3.5\tensornets\datasets
  copying tensornets\references\coco.names -> build\lib.win-amd64-3.5\tensornets\references
  copying tensornets\references\voc.names -> build\lib.win-amd64-3.5\tensornets\references
  copying tensornets\references\darkflow_utils\get_boxes.pyx -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\nms.pxd -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\nms.pyx -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
  running build_ext
  building 'tensornets.references.darkflow_utils.nms' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

  ----------------------------------------
  Failed building wheel for tensornets
  Running setup.py clean for tensornets
Failed to build tensornets
Installing collected packages: tensornets
  Running setup.py install for tensornets ... error
    Complete output from command c:\programdata\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\admin\\AppData\\Local\\Temp\\pip-req-build-pslh3n1z\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\admin\AppData\Local\Temp\pip-record-tgoomb1b\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\tensornets
    copying tensornets\capsulenets.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\darknets.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\densenets.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\detections.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\inceptions.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\layers.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\middles.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\mobilenets.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\nasnets.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\ops.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\preprocess.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\pretrained.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\resnets.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\squeezenets.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\utils.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\vggs.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\wavenets.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\zf.py -> build\lib.win-amd64-3.5\tensornets
    copying tensornets\__init__.py -> build\lib.win-amd64-3.5\tensornets
    creating build\lib.win-amd64-3.5\tensornets\datasets
    copying tensornets\datasets\coco.py -> build\lib.win-amd64-3.5\tensornets\datasets
    copying tensornets\datasets\imagenet.py -> build\lib.win-amd64-3.5\tensornets\datasets
    copying tensornets\datasets\voc.py -> build\lib.win-amd64-3.5\tensornets\datasets
    copying tensornets\datasets\__init__.py -> build\lib.win-amd64-3.5\tensornets\datasets
    creating build\lib.win-amd64-3.5\tensornets\references
    copying tensornets\references\rcnns.py -> build\lib.win-amd64-3.5\tensornets\references
    copying tensornets\references\rpn_utils.py -> build\lib.win-amd64-3.5\tensornets\references
    copying tensornets\references\yolos.py -> build\lib.win-amd64-3.5\tensornets\references
    copying tensornets\references\yolo_utils.py -> build\lib.win-amd64-3.5\tensornets\references
    copying tensornets\references\__init__.py -> build\lib.win-amd64-3.5\tensornets\references
    creating build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\box.py -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\__init__.py -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    running egg_info
    writing dependency_links to tensornets.egg-info\dependency_links.txt
    writing tensornets.egg-info\PKG-INFO
    writing top-level names to tensornets.egg-info\top_level.txt
    reading manifest file 'tensornets.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'tensornets.egg-info\SOURCES.txt'
    copying tensornets\references\darkflow_utils\get_boxes.c -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\nms.c -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    copying tensornets\datasets\coco.names -> build\lib.win-amd64-3.5\tensornets\datasets
    copying tensornets\datasets\voc.names -> build\lib.win-amd64-3.5\tensornets\datasets
    copying tensornets\references\coco.names -> build\lib.win-amd64-3.5\tensornets\references
    copying tensornets\references\voc.names -> build\lib.win-amd64-3.5\tensornets\references
    copying tensornets\references\darkflow_utils\get_boxes.pyx -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\nms.pxd -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    copying tensornets\references\darkflow_utils\nms.pyx -> build\lib.win-amd64-3.5\tensornets\references\darkflow_utils
    running build_ext
    building 'tensornets.references.darkflow_utils.nms' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "c:\programdata\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\admin\\AppData\\Local\\Temp\\pip-req-build-pslh3n1z\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\admin\AppData\Local\Temp\pip-record-tgoomb1b\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\admin\AppData\Local\Temp\pip-req-build-pslh3n1z\

Kindly help

**Comment by taehoonlee** [comment]
Thank you for trying TensorNets, @rohtash0211. But the error message is `error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools"`. It doesn't seem to be a TensorNets issue.

**Comment by rohtash0211** [comment]
Hi,

Tensornets is working fine on another machine with the same
configuration. Microsoft
Visual C++ 14.0 is not installed on another machine.

Kindly suggest


Thanks and Regards,
*Rohtash Chaudhary*
Tel. 8588803184, 9818959484
rohtash0211@gmail.com

**Comment by taehoonlee** [comment]
Thank you, @rohtash0211!

**Comment by avinashkr29** [comment]
Hello @taehoonlee , I am facing same issue. Please help. VC++ is installed on my pc, and I didn't get error with any other package. 
 pip install tensornets
Collecting tensornets
  Using cached tensornets-0.4.6.tar.gz (651 kB)
  Installing build dependencies ... done
  WARNING: Missing build requirements in pyproject.toml for tensornets from https://files.pythonhosted.org/packages/71/22/2c9402bbf142b94dc39d8a3c9884690ae87706a8bc1453d6cf0630525173/tensornets-0.4.6.tar.gz#sha256=e1095082b45a06168d56450d8c8fa49780d8aef8d4d1fcc64efceadb743f9ceb.
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: tensornets
  Building wheel for tensornets (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\envs\yolov3-tf2-cpu\python.exe' 'C:\ProgramData\Anaconda3\envs\yolov3-tf2-cpu\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\kpjz923\AppData\Local\Temp\tmpwhqwclvl'
       cwd: C:\Users\kpjz923\AppData\Local\Temp\pip-install-0_xh1ftt\tensornets
  Complete output (80 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\tensornets
  copying tensornets\capsulenets.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\darknets.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\densenets.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\detections.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\efficientnets.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\inceptions.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\layers.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\middles.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\mobilenets.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\nasnets.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\ops.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\preprocess.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\pretrained.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\resnets.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\squeezenets.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\tnets.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\unet.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\utils.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\version_utils.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\vggs.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\wavenets.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\zf.py -> build\lib.win-amd64-3.7\tensornets
  copying tensornets\__init__.py -> build\lib.win-amd64-3.7\tensornets
  creating build\lib.win-amd64-3.7\tensornets\datasets
  copying tensornets\datasets\coco.py -> build\lib.win-amd64-3.7\tensornets\datasets
  copying tensornets\datasets\imagenet.py -> build\lib.win-amd64-3.7\tensornets\datasets
  copying tensornets\datasets\voc.py -> build\lib.win-amd64-3.7\tensornets\datasets
  copying tensornets\datasets\__init__.py -> build\lib.win-amd64-3.7\tensornets\datasets
  creating build\lib.win-amd64-3.7\tensornets\contrib_framework
  copying tensornets\contrib_framework\arg_scope.py -> build\lib.win-amd64-3.7\tensornets\contrib_framework
  copying tensornets\contrib_framework\variables.py -> build\lib.win-amd64-3.7\tensornets\contrib_framework
  copying tensornets\contrib_framework\__init__.py -> build\lib.win-amd64-3.7\tensornets\contrib_framework
  creating build\lib.win-amd64-3.7\tensornets\contrib_layers
  copying tensornets\contrib_layers\initializers.py -> build\lib.win-amd64-3.7\tensornets\contrib_layers
  copying tensornets\contrib_layers\layers.py -> build\lib.win-amd64-3.7\tensornets\contrib_layers
  copying tensornets\contrib_layers\normalization.py -> build\lib.win-amd64-3.7\tensornets\contrib_layers
  copying tensornets\contrib_layers\optimizers.py -> build\lib.win-amd64-3.7\tensornets\contrib_layers
  copying tensornets\contrib_layers\regularizers.py -> build\lib.win-amd64-3.7\tensornets\contrib_layers
  copying tensornets\contrib_layers\rev_block_lib.py -> build\lib.win-amd64-3.7\tensornets\contrib_layers
  copying tensornets\contrib_layers\summaries.py -> build\lib.win-amd64-3.7\tensornets\contrib_layers
  copying tensornets\contrib_layers\utils.py -> build\lib.win-amd64-3.7\tensornets\contrib_layers
  copying tensornets\contrib_layers\__init__.py -> build\lib.win-amd64-3.7\tensornets\contrib_layers
  creating build\lib.win-amd64-3.7\tensornets\references
  copying tensornets\references\rcnns.py -> build\lib.win-amd64-3.7\tensornets\references
  copying tensornets\references\rpn_utils.py -> build\lib.win-amd64-3.7\tensornets\references
  copying tensornets\references\yolos.py -> build\lib.win-amd64-3.7\tensornets\references
  copying tensornets\references\yolo_utils.py -> build\lib.win-amd64-3.7\tensornets\references
  copying tensornets\references\__init__.py -> build\lib.win-amd64-3.7\tensornets\references
  creating build\lib.win-amd64-3.7\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\box.py -> build\lib.win-amd64-3.7\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\__init__.py -> build\lib.win-amd64-3.7\tensornets\references\darkflow_utils
  running egg_info
  writing tensornets.egg-info\PKG-INFO
  writing dependency_links to tensornets.egg-info\dependency_links.txt
  writing top-level names to tensornets.egg-info\top_level.txt
  reading manifest file 'tensornets.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'tensornets.egg-info\SOURCES.txt'
  copying tensornets\references\darkflow_utils\get_boxes.c -> build\lib.win-amd64-3.7\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\nms.c -> build\lib.win-amd64-3.7\tensornets\references\darkflow_utils
  copying tensornets\datasets\coco.names -> build\lib.win-amd64-3.7\tensornets\datasets
  copying tensornets\datasets\voc.names -> build\lib.win-amd64-3.7\tensornets\datasets
  copying tensornets\references\coco.names -> build\lib.win-amd64-3.7\tensornets\references
  copying tensornets\references\voc.names -> build\lib.win-amd64-3.7\tensornets\references
  copying tensornets\references\darkflow_utils\__init__.pyc -> build\lib.win-amd64-3.7\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\box.pyc -> build\lib.win-amd64-3.7\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\get_boxes.pyx -> build\lib.win-amd64-3.7\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\get_boxes.so -> build\lib.win-amd64-3.7\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\nms.pxd -> build\lib.win-amd64-3.7\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\nms.pyx -> build\lib.win-amd64-3.7\tensornets\references\darkflow_utils
  copying tensornets\references\darkflow_utils\nms.so -> build\lib.win-amd64-3.7\tensornets\references\darkflow_utils
  running build_ext
  building 'tensornets.references.darkflow_utils.nms' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for tensornets
Failed to build tensornets
ERROR: Could not build wheels for tensornets which use PEP 517 and cannot be installed directly

**Comment by nicomunting** [comment]
Do the other packages, which install succesfully, contain Cython code? Because the nms extension on which it appears to get stuck does not contain regular Python code.
