### ISSUE TITLE
custom weights for tensornet model

### ISSUE THREAD

**Issue by vladdders** [taehoonlee/tensornets#57]
Hi, is it possible to load custom weights in tensornets models? Say I have some different classes than the ones in coco dataset for a yolov3 model and I'd like to load them using tensornets. Is that doable?

Thanks in advance!

**Comment by taehoonlee** [comment]
Thank you for using TensorNets, @vladdders. In order to use the following APIs, you should upgrade `tensornets==0.4.5`.

```python
with tf.Session() as sess:
    model.init()
    # ... your training ...
    model.save('test.npz')

with tf.Session() as sess:
    model.load('test.npz')
    # ... your deployment ...
```

Or, you can simply use the following patterns.
```
np.save('test.npy', sess.run(model.weights()))  # save
sess.run([w.assign(v) for (w, v) in zip(model.weights(), np.load('test.npy'))])  # load
```

**Comment by taehoonlee** [comment]
@vladdders, I'll close the issue for now. Please feel free to open it again at any time if you have additional comments.
