### ISSUE TITLE
detection scripts error

### ISSUE THREAD

**Issue by alain2208** [taehoonlee/tensornets#6]
hi with windows got this error when trying your detection script 
is there something missing.
installed with pip
AssertionError: `get_boxes` requires `darkflow`

**Comment by taehoonlee** [comment]
@alain2208, Can you try `pip install git+https://github.com/thtrieu/darkflow` (maybe requires `pip install cython`)? I have not tried it on Windows yet.

**Comment by alain2208** [comment]
works now ....with darkflow install trick  this no more shout for this one .... but another one . 
think yolo_utils.py was developped for python2.7 as i have a crash for xrange under python 3.5. who don't use xrange anymore.
maybe i should open another case for the yolo_utils

BTW great job

**Comment by taehoonlee** [comment]
@alain2208, The issue has been resolved by #7. If you want to use the latest version, you can try `pip install -U --no-deps git+https://github.com/taehoonlee/tensornets`. Thank you for the comments!
