### ISSUE TITLE
README's "A quick example" get error.

### ISSUE THREAD

**Issue by inoue0426** [taehoonlee/tensornets#9]
"from tensornets import utils
img = utils.load_img('cat.png', target_size=256, crop_size=224)
assert img.shape == (1, 224, 224, 3)"

This script get error.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-cfc591717955> in <module>()
      1 from tensornets import utils
----> 2 img = utils.load_img('cat.png', target_size=256, crop_size=224)
      3 assert img.shape == (1, 224, 224, 3)

~/.conda/envs/tensor/lib/python3.6/site-packages/tensornets/utils.py in load_img(path, grayscale, target_size, crop_size, interp)
    176         if isinstance(target_size, int):
    177             hw_tuple = tuple([x * target_size // min(img.shape[:2])
--> 178                               for x in img.shape[1::-1]])
    179         else:
    180             hw_tuple = (target_size[1], target_size[0])

AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by alain2208** [comment]
got the same under windows i copy one of my pic and defined the complete path to find the image. worked well

**Comment by taehoonlee** [comment]
@inoue0426, It doesn't seem to be a TensorNets issue. You can try the sample codes on the directory where the `cat.png` exists. Or, you can also give the complete path as @alain2208 said.
